baseURL = 'https://rivieradev2024-crazytrain.netlify.app/'
languageCode = 'en-us'
title = 'Riviera Dev 2024 - Lab "Crazy Train"'

theme = 'hugo-theme-learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "red"
openshift_domain = "riviera-dev-2024.sandbox2830.opentlc.com"
minioPass = "minio123"
minioEndpoint = "https://minio-s3-minio.apps.riviera-dev-2024.sandbox2830.opentlc.com"
minioConsole = "https://minio-console-minio.apps.riviera-dev-2024.sandbox2830.opentlc.com"
gitRepoName = "workshop-model-training"
gitAIRepoUrl = "https://github.com/Demo-AI-Edge-Crazy-Train/workshop-model-training"
baseModelBucket = "model-registry"
newModelName = "new"
newModelServerName = "Traffic Sign Detection"
newModelDataConnection = "pipelines"
newModelPath = "models/model.onnx"
newModelServerSize = "Small"

# Anglais est la langue par défaut
defaultContentLanguage = "fr"
# Force d'avoir /en/ma-page et /fr/ma-page routes, même avec la langue par défaut.
defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"